# Generated by Django 5.1.5 on 2025-01-28 14:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
