# Generated by Django 5.1.5 on 2025-01-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_alter_destination_img_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='destination_name',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travello.destination'),
        ),
    ]
