# Generated by Django 5.1.5 on 2025-01-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_rename_destination_name_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='travello.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.destination'),
        ),
    ]
