# Generated by Django 5.1.5 on 2025-01-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_alter_comments_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
    ]
