# Generated by Django 5.1.5 on 2025-01-29 11:36

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_remove_comments_parent_comments_parent_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travello.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='destinations/'),
        ),
    ]
