# Generated by Django 5.1.5 on 2025-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_remove_comments_parent_comment_comments_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.TextField(default=''),
        ),
    ]
